export const ProjectFactoryABI = [
  {
    inputs: [{ internalType: 'address', name: '_usdc', type: 'address' }],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  { inputs: [], name: 'FailedDeployment', type: 'error' },
  {
    inputs: [
      { internalType: 'uint256', name: 'balance', type: 'uint256' },
      { internalType: 'uint256', name: 'needed', type: 'uint256' },
    ],
    name: 'InsufficientBalance',
    type: 'error',
  },
  { inputs: [], name: 'InvalidDescription', type: 'error' },
  { inputs: [], name: 'InvalidInitialPrice', type: 'error' },
  { inputs: [], name: 'InvalidTargetMarketCap', type: 'error' },
  { inputs: [], name: 'InvalidTimeLimit', type: 'error' },
  { inputs: [], name: 'InvalidTokenAmount', type: 'error' },
  {
    inputs: [{ internalType: 'address', name: 'token', type: 'address' }],
    name: 'SafeERC20FailedOperation',
    type: 'error',
  },
  { inputs: [], name: 'TemplatesAlreadySet', type: 'error' },
  { inputs: [], name: 'TemplatesNotSet', type: 'error' },
  { inputs: [], name: 'ZeroAddress', type: 'error' },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'project',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'owner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'token',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'enum IProjectFactory.PoolMode',
        name: 'mode',
        type: 'uint8',
      },
    ],
    name: 'ProjectCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'directPoolTemplate',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'bondingCurveTemplate',
        type: 'address',
      },
    ],
    name: 'TemplatesSet',
    type: 'event',
  },
  {
    inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    name: 'allProjects',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'bondingCurveTemplate',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bool', name: 'isNewToken', type: 'bool' },
      { internalType: 'address', name: 'existingToken', type: 'address' },
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'symbol', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'uint256', name: 'tokenAmount', type: 'uint256' },
      {
        internalType: 'enum IProjectFactory.PoolMode',
        name: 'mode',
        type: 'uint8',
      },
      { internalType: 'uint256', name: 'initialPrice', type: 'uint256' },
      { internalType: 'uint256', name: 'targetMarketCap', type: 'uint256' },
      { internalType: 'uint256', name: 'borrowTimeLimit', type: 'uint256' },
    ],
    name: 'createProject',
    outputs: [
      { internalType: 'address', name: 'projectAddress', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'directPoolTemplate',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getAllProjects',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getProjectCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'project', type: 'address' }],
    name: 'getProjectMode',
    outputs: [
      {
        internalType: 'enum IProjectFactory.PoolMode',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
    name: 'getProjectsByOwner',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'projectModes',
    outputs: [
      {
        internalType: 'enum IProjectFactory.PoolMode',
        name: '',
        type: 'uint8',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '', type: 'address' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'projectsByOwner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_directPoolTemplate', type: 'address' },
      {
        internalType: 'address',
        name: '_bondingCurveTemplate',
        type: 'address',
      },
    ],
    name: 'setTemplates',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'usdc',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;
